name: oobdex
description: An UNOFFICIAL Ooblets index to help reach the completion of this fantastic game.

publish_to: "none"

version: "0.0.1"

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  badges: ^3.0.2
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.5+1
  flutter_localizations:
    sdk: flutter
  flutter_redux: ^0.10.0
  font_awesome_flutter: ^10.2.1
  get_it: ^7.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^0.13.5
  intl: ^0.17.0
  logger: ^1.1.0
  meta: ^1.8.0
  mutex: ^3.0.0
  redux: ^5.0.0
  shared_preferences: ^2.0.15
  url_launcher: ^6.1.6

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true
